// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opbtgphcxfqthzfzqzxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wYnRncGhjeGZxdGh6ZnpxenhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjQxMzAsImV4cCI6MjA2MDIwMDEzMH0.lAW_-0TdDXPdKiAIk773jfaAHTRgqPU92kxc0TforUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);